/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import montg3i.Hotel;
import montg3i.Guest;
import montg3i.Manager;
import montg3i.ReceptionEmployee;
import montg3i.Staff;

/**
 *
 * @author hp
 */
public class BalanceAndReservations extends javax.swing.JFrame {

    /**
     * Creates new form BalanceAndReservations
     */
    public BalanceAndReservations() {
        initComponents();
        btnBack.setBackground(new Color(0,0,0,0));
        
        ArrayList<Guest> g = Hotel.getGuestList();
        ArrayList<Staff> m = Hotel.getManagerList();
        ArrayList<Staff> r = Hotel.getReceptionEmployeeList();
        double TotalBalance = 0;
        
        DefaultTableModel model = (DefaultTableModel)TableOfGuests.getModel();
        for(int i=0; i<g.size(); i++)
        {
            model.insertRow(model.getRowCount(), new Object[]{g.get(i).getFirstName(), g.get(i).getNational(), g.get(i).getNumbersOfRooms(), g.get(i).getDeparture(), g.get(i).getNights()}); 
            TotalBalance += g.get(i).getTotalAmount();
        }
        
        for(int i=0; i<m.size(); i++)
        {
            TotalBalance -= m.get(i).getSalary();
        }
        for(int i=0; i<r.size(); i++)
        {
            TotalBalance -= r.get(i).getSalary();
        }
        
        TotalBalanceLabel.setText(TotalBalance + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TotalBalance = new javax.swing.JLabel();
        TotalBalanceLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableOfGuests = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1550, 805));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        TotalBalance.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        TotalBalance.setForeground(new java.awt.Color(255, 255, 255));
        TotalBalance.setText("Total Balance:");
        jPanel1.add(TotalBalance);
        TotalBalance.setBounds(40, 60, 210, 40);

        TotalBalanceLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        TotalBalanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        TotalBalanceLabel.setText("jLabel1");
        jPanel1.add(TotalBalanceLabel);
        TotalBalanceLabel.setBounds(280, 60, 120, 40);

        TableOfGuests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Nationality", "number of Rooms", "Date", "Number of Nights"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableOfGuests);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(640, 0, 730, 750);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/OP2.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 370, 390, 220);

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("< Back");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(70, 619, 110, 40);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/OP1.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 200, 390, 180);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1530, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new ManagerProfile().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalanceAndReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalanceAndReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalanceAndReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalanceAndReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalanceAndReservations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableOfGuests;
    private javax.swing.JLabel TotalBalance;
    private javax.swing.JLabel TotalBalanceLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
