package frames;


import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class GuestProfile extends javax.swing.JFrame {

    /**
     * Creates new form GuestProfile
     */
    public GuestProfile() {
        initComponents();
    }
    public GuestProfile(String x,String y,String r,String e) {
        initComponents();
        NameLabel.setText(x);
        RoomNoLabel.setText(y);
        FloorLabel.setText(r);
        
        btnGuestPayment.isSelected();
        //jTextArea1.append("hi");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        RoomNo = new javax.swing.JLabel();
        RoomNoLabel = new javax.swing.JLabel();
        Floor = new javax.swing.JLabel();
        FloorLabel = new javax.swing.JLabel();
        btnEntertainment = new javax.swing.JButton();
        btnUpdateTheReservation = new javax.swing.JButton();
        btnGuestPayment = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile");
        setLocation(new java.awt.Point(700, 300));

        Name.setText("Name:");

        NameLabel.setText("jLabel2");

        RoomNo.setText("Room/s No.:");

        RoomNoLabel.setText("jLabel4");

        Floor.setText("Floor:");

        FloorLabel.setText("jLabel8");

        btnEntertainment.setText("Entertainment");
        btnEntertainment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntertainment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntertainmentActionPerformed(evt);
            }
        });

        btnUpdateTheReservation.setText("Update The Reservation");
        btnUpdateTheReservation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateTheReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTheReservationActionPerformed(evt);
            }
        });

        btnGuestPayment.setText("The Payment");
        btnGuestPayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuestPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuestPaymentActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Floor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FloorLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLogout)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Name)
                                .addGap(18, 18, 18)
                                .addComponent(NameLabel)))
                        .addGap(68, 68, 68)
                        .addComponent(RoomNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RoomNoLabel)))
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdateTheReservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEntertainment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuestPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(NameLabel)
                    .addComponent(RoomNo)
                    .addComponent(RoomNoLabel))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Floor)
                    .addComponent(FloorLabel))
                .addGap(18, 18, 18)
                .addComponent(btnEntertainment)
                .addGap(35, 35, 35)
                .addComponent(btnUpdateTheReservation)
                .addGap(28, 28, 28)
                .addComponent(btnGuestPayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuestPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuestPaymentActionPerformed

        if(NameLabel.getText()=="she5 L 3arab")
        {
            int x=8,y=9;
            showMessageDialog(null,"Payed: "+x+"\n"+"Rest Amount: "+y);
            
        }
        
    }//GEN-LAST:event_btnGuestPaymentActionPerformed

    private void btnUpdateTheReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTheReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateTheReservationActionPerformed

    private void btnEntertainmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntertainmentActionPerformed
        new Entertainment().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEntertainmentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new Guest().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestProfile().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Floor;
    private javax.swing.JLabel FloorLabel;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel RoomNo;
    private javax.swing.JLabel RoomNoLabel;
    private javax.swing.JButton btnEntertainment;
    private javax.swing.JButton btnGuestPayment;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateTheReservation;
    // End of variables declaration//GEN-END:variables
}
