package frames;


import java.awt.Color;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class GuestProfile extends javax.swing.JFrame {

    /**
     * Creates new form GuestProfile
     */
    public GuestProfile() {
        initComponents();
        btnEntertainment.setBackground(new Color(0,0,0,0));
        btnGuestPayment.setBackground(new Color(0,0,0,0));
        btnUpdateTheReservation.setBackground(new Color(0,0,0,0));
        btnLogout.setBackground(new Color(0,0,0,0));
    }
   /* public GuestProfile(String x,String y,String r,String e) {
        initComponents();
        NameLabel.setText(x);
        RoomNoLabel.setText(y);
        FloorLabel.setText(r);
        
        btnGuestPayment.isSelected();
        //jTextArea1.append("hi");
        
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Floor = new javax.swing.JLabel();
        FloorLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        RoomNo = new javax.swing.JLabel();
        RoomNoLabel = new javax.swing.JLabel();
        btnEntertainment = new javax.swing.JButton();
        btnUpdateTheReservation = new javax.swing.JButton();
        btnGuestPayment = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1494, 816));
        setSize(new java.awt.Dimension(1520, 845));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Name.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name:");

        Floor.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Floor.setForeground(new java.awt.Color(255, 255, 255));
        Floor.setText("Floor:");

        FloorLabel.setForeground(new java.awt.Color(255, 255, 255));
        FloorLabel.setText("jLabel8");

        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("jLabel2");

        RoomNo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        RoomNo.setForeground(new java.awt.Color(255, 255, 255));
        RoomNo.setText("Room/s No.:");

        RoomNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        RoomNoLabel.setText("jLabel4");

        btnEntertainment.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnEntertainment.setForeground(new java.awt.Color(255, 255, 255));
        btnEntertainment.setText(">  Entertainment");
        btnEntertainment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntertainment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntertainment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntertainmentActionPerformed(evt);
            }
        });

        btnUpdateTheReservation.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnUpdateTheReservation.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateTheReservation.setText(">  Update The Reservation");
        btnUpdateTheReservation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateTheReservation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateTheReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTheReservationActionPerformed(evt);
            }
        });

        btnGuestPayment.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnGuestPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnGuestPayment.setText(">  The Payment");
        btnGuestPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuestPayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuestPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuestPaymentActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("< Logout");
        btnLogout.setBorder(null);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Floor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FloorLabel))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Name)
                            .addGap(35, 35, 35)
                            .addComponent(NameLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RoomNo)
                        .addGap(30, 30, 30)
                        .addComponent(RoomNoLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuestPayment)
                    .addComponent(btnUpdateTheReservation)
                    .addComponent(btnEntertainment))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name)
                            .addComponent(NameLabel))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Floor)
                            .addComponent(FloorLabel))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RoomNo)
                            .addComponent(RoomNoLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnEntertainment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateTheReservation)
                        .addGap(1, 1, 1)
                        .addComponent(btnGuestPayment)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 230, 760, 320);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/5.jpg"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -4, 1500, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuestPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuestPaymentActionPerformed

        if(NameLabel.getText()=="she5 L 3arab")
        {
            int x=8,y=9;
            showMessageDialog(null,"Payed: "+x+"\n"+"Rest Amount: "+y);
            
        }
        
    }//GEN-LAST:event_btnGuestPaymentActionPerformed

    private void btnUpdateTheReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTheReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateTheReservationActionPerformed

    private void btnEntertainmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntertainmentActionPerformed
        new Entertainment().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEntertainmentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new Guest().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestProfile().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Floor;
    private javax.swing.JLabel FloorLabel;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel RoomNo;
    private javax.swing.JLabel RoomNoLabel;
    private javax.swing.JButton btnEntertainment;
    private javax.swing.JButton btnGuestPayment;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateTheReservation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
