package frames;


import java.awt.Color;
import java.util.ArrayList;
import static javax.swing.JOptionPane.showMessageDialog;
import montg3i.Hotel;

import montg3i.HotelRoom;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class GuestProfile extends javax.swing.JFrame {

    /**
     * Creates new form GuestProfile
     */
    public GuestProfile() {
        initComponents();
        btnEntertainment.setBackground(new Color(0,0,0,0));
        btnGuestPayment.setBackground(new Color(0,0,0,0));
        btnUpdateTheReservation.setBackground(new Color(0,0,0,0));
        btnLogout.setBackground(new Color(0,0,0,0));
        
        ArrayList<montg3i.Guest> g = Hotel.getGuestList();
        
        //NameLabel.setText(g.get(montg3i.Guest.getCurrentGuestNo()).getFirstName() + " " + g.get(montg3i.Guest.getCurrentGuestNo()).getLastName());
        RoomNoLabel.setText(HotelRoom.Search(montg3i.Guest.getCurrentGuestNo()));
        
    }
   /* public GuestProfile(String x,String y,String r,String e) {
        initComponents();
        NameLabel.setText(x);
        RoomNoLabel.setText(y);
        FloorLabel.setText(r);
        
        btnGuestPayment.isSelected();
        //jTextArea1.append("hi");
        
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        RoomNo = new javax.swing.JLabel();
        RoomNoLabel = new javax.swing.JLabel();
        btnEntertainment = new javax.swing.JButton();
        btnUpdateTheReservation = new javax.swing.JButton();
        btnGuestPayment = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Floor = new javax.swing.JLabel();
        FloorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1516, 849));
        setSize(new java.awt.Dimension(1520, 845));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        Name.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name:");
        jPanel1.add(Name);
        Name.setBounds(98, 42, 75, 34);

        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("jLabel2");
        jPanel1.add(NameLabel);
        NameLabel.setBounds(270, 50, 34, 15);

        RoomNo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        RoomNo.setForeground(new java.awt.Color(255, 255, 255));
        RoomNo.setText("Room/s No.:");
        jPanel1.add(RoomNo);
        RoomNo.setBounds(80, 140, 147, 34);

        RoomNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        RoomNoLabel.setText("jLabel4");
        jPanel1.add(RoomNoLabel);
        RoomNoLabel.setBounds(270, 150, 34, 15);

        btnEntertainment.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnEntertainment.setForeground(new java.awt.Color(255, 255, 255));
        btnEntertainment.setText(">  Entertainment");
        btnEntertainment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntertainment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntertainment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntertainmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntertainmentMouseExited(evt);
            }
        });
        btnEntertainment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntertainmentActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntertainment);
        btnEntertainment.setBounds(410, 60, 233, 44);

        btnUpdateTheReservation.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnUpdateTheReservation.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateTheReservation.setText(">  Update The Reservation");
        btnUpdateTheReservation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateTheReservation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateTheReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateTheReservationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateTheReservationMouseExited(evt);
            }
        });
        btnUpdateTheReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTheReservationActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateTheReservation);
        btnUpdateTheReservation.setBounds(410, 120, 350, 44);

        btnGuestPayment.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnGuestPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnGuestPayment.setText(">  The Payment");
        btnGuestPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuestPayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuestPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuestPaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuestPaymentMouseExited(evt);
            }
        });
        btnGuestPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuestPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuestPayment);
        btnGuestPayment.setBounds(410, 180, 218, 44);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(400, 60, 10, 170);

        btnLogout.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("< Logout");
        btnLogout.setBorder(null);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(38, 257, 100, 34);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 230, 760, 320);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/5.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -4, 1500, 800);

        Floor.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Floor.setForeground(new java.awt.Color(255, 255, 255));
        Floor.setText("Floor:");
        getContentPane().add(Floor);
        Floor.setBounds(950, 430, 70, 34);

        FloorLabel.setForeground(new java.awt.Color(255, 255, 255));
        FloorLabel.setText("jLabel8");
        getContentPane().add(FloorLabel);
        FloorLabel.setBounds(1000, 320, 34, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuestPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuestPaymentActionPerformed

        if(NameLabel.getText()=="she5 L 3arab")
        {
            int x=8,y=9;
            showMessageDialog(null,"Payed: "+x+"\n"+"Rest Amount: "+y);
            
        }
        
    }//GEN-LAST:event_btnGuestPaymentActionPerformed

    private void btnUpdateTheReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTheReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateTheReservationActionPerformed

    private void btnEntertainmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntertainmentActionPerformed
        new Entertainment().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEntertainmentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new Guest().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnEntertainmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntertainmentMouseEntered
        btnEntertainment.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnEntertainmentMouseEntered

    private void btnEntertainmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntertainmentMouseExited
        btnEntertainment.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnEntertainmentMouseExited

    private void btnUpdateTheReservationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateTheReservationMouseEntered
        btnUpdateTheReservation.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnUpdateTheReservationMouseEntered

    private void btnUpdateTheReservationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateTheReservationMouseExited
        btnUpdateTheReservation.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnUpdateTheReservationMouseExited

    private void btnGuestPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuestPaymentMouseEntered
        btnGuestPayment.setForeground(Color.LIGHT_GRAY);   
    }//GEN-LAST:event_btnGuestPaymentMouseEntered

    private void btnGuestPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuestPaymentMouseExited
        btnGuestPayment.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnGuestPaymentMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        btnLogout.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        btnLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnLogoutMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestProfile().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Floor;
    private javax.swing.JLabel FloorLabel;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel RoomNo;
    private javax.swing.JLabel RoomNoLabel;
    private javax.swing.JButton btnEntertainment;
    private javax.swing.JButton btnGuestPayment;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateTheReservation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
