package frames;

import java.awt.BorderLayout;
import java.awt.Color;
import org.opencv.core.Core;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class ManagerProfile extends javax.swing.JFrame {

    /**
     * Creates new form SearchOnReservation
     */
    public ManagerProfile() {
        initComponents();
        btnBalanceAndReservations.setBackground(new Color(0,0,0,0));
        btnCameras.setBackground(new Color(0,0,0,0));
        btnEmployee.setBackground(new Color(0,0,0,0));
        btnLogout.setBackground(new Color(0,0,0,0));
        btnNewEmployee.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNewEmployee = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnCameras = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnBalanceAndReservations = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1520, 850));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        btnNewEmployee.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnNewEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnNewEmployee.setText("New Employees");
        btnNewEmployee.setBorder(null);
        btnNewEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewEmployee);
        btnNewEmployee.setBounds(130, 360, 280, 40);

        btnEmployee.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployee.setText("Employee");
        btnEmployee.setBorder(null);
        btnEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmployee);
        btnEmployee.setBounds(170, 240, 190, 43);

        btnCameras.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnCameras.setForeground(new java.awt.Color(255, 255, 255));
        btnCameras.setText("Cameras");
        btnCameras.setBorder(null);
        btnCameras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCameras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamerasActionPerformed(evt);
            }
        });
        jPanel1.add(btnCameras);
        btnCameras.setBounds(180, 480, 180, 40);

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("<  Logout");
        btnLogout.setBorder(null);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(180, 600, 180, 40);

        btnBalanceAndReservations.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnBalanceAndReservations.setForeground(new java.awt.Color(255, 255, 255));
        btnBalanceAndReservations.setText("Balance and Reservations");
        btnBalanceAndReservations.setBorder(null);
        btnBalanceAndReservations.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBalanceAndReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceAndReservationsActionPerformed(evt);
            }
        });
        jPanel1.add(btnBalanceAndReservations);
        btnBalanceAndReservations.setBounds(40, 130, 430, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(250, 0, 520, 800);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/p10.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1500, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        //new Receiption().setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnBalanceAndReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceAndReservationsActionPerformed
         new BalanceAndReservations().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_btnBalanceAndReservationsActionPerformed

    private void btnNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewEmployeeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
         new Login().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCamerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamerasActionPerformed
         new CCTV().setVisible(true);
    }//GEN-LAST:event_btnCamerasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ManagerProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBalanceAndReservations;
    private javax.swing.JButton btnCameras;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
