package frames;


import java.awt.Color;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Receiptionist extends javax.swing.JFrame {

    /**
     * Creates new form Receiptionist
     */
    public Receiptionist() {
        initComponents();
        btnSend.setBackground(new Color(0,0,0,0));
        btnLogout.setBackground(new Color(0,0,0,0));
        btnSalary.setBackground(new Color(0,0,0,0));
        btnVacation.setBackground(new Color(0,0,0,0));
        btnInsurance.setBackground(new Color(0,0,0,0));
        btnFeaturesAndOffers.setBackground(new Color(0,0,0,0));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnInsurance = new javax.swing.JButton();
        btnFeaturesAndOffers = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ComplainsBox = new javax.swing.JTextArea();
        btnLogout = new javax.swing.JButton();
        Complains = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        btnSalary = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        btnVacation = new javax.swing.JButton();
        PositionLabel = new javax.swing.JLabel();
        Position = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1520, 845));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        btnInsurance.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnInsurance.setForeground(new java.awt.Color(255, 255, 255));
        btnInsurance.setText("> Insurance");
        btnInsurance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsuranceActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsurance);
        btnInsurance.setBounds(180, 310, 140, 35);

        btnFeaturesAndOffers.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnFeaturesAndOffers.setForeground(new java.awt.Color(255, 255, 255));
        btnFeaturesAndOffers.setText("> Features and Offers");
        btnFeaturesAndOffers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFeaturesAndOffers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeaturesAndOffersActionPerformed(evt);
            }
        });
        jPanel2.add(btnFeaturesAndOffers);
        btnFeaturesAndOffers.setBounds(180, 270, 240, 35);

        Name.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name:");
        jPanel2.add(Name);
        Name.setBounds(80, 120, 57, 26);

        ComplainsBox.setColumns(20);
        ComplainsBox.setRows(5);
        jScrollPane1.setViewportView(ComplainsBox);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(170, 450, 220, 137);

        btnLogout.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("< Logout");
        btnLogout.setBorder(null);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout);
        btnLogout.setBounds(30, 700, 110, 43);

        Complains.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Complains.setForeground(new java.awt.Color(255, 255, 255));
        Complains.setText("Complains:");
        jPanel2.add(Complains);
        Complains.setBounds(80, 450, 90, 26);

        btnSend.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("SEND");
        btnSend.setBorder(null);
        btnSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSendMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSendMouseExited(evt);
            }
        });
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        jPanel2.add(btnSend);
        btnSend.setBounds(200, 610, 130, 40);

        btnSalary.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnSalary.setForeground(new java.awt.Color(255, 255, 255));
        btnSalary.setText("> Salary");
        btnSalary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaryActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalary);
        btnSalary.setBounds(180, 390, 110, 35);

        NameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("Zatona");
        jPanel2.add(NameLabel);
        NameLabel.setBounds(170, 120, 80, 20);

        ID.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.setText("ID:");
        jPanel2.add(ID);
        ID.setBounds(80, 160, 31, 26);

        IDLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        IDLabel.setForeground(new java.awt.Color(255, 255, 255));
        IDLabel.setText("996778899");
        jPanel2.add(IDLabel);
        IDLabel.setBounds(170, 160, 120, 20);

        btnVacation.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnVacation.setForeground(new java.awt.Color(255, 255, 255));
        btnVacation.setText("> Vacation");
        btnVacation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnVacation);
        btnVacation.setBounds(180, 350, 130, 35);

        PositionLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        PositionLabel.setForeground(new java.awt.Color(255, 255, 255));
        PositionLabel.setText("Receiptionist Class A");
        jPanel2.add(PositionLabel);
        PositionLabel.setBounds(170, 200, 190, 20);

        Position.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Position.setForeground(new java.awt.Color(255, 255, 255));
        Position.setText("Position:");
        jPanel2.add(Position);
        Position.setBounds(80, 200, 72, 26);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Profile");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(240, 40, 160, 31);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/icons8_contacts_64px_1.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(160, 20, 70, 70);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(80, 240, 360, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(480, 0, 510, 790);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/6.jpg"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1500, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaryActionPerformed
        double salary=7000;
        showMessageDialog(null,"Your Salary is "+salary+" $");
    }//GEN-LAST:event_btnSalaryActionPerformed

    private void btnFeaturesAndOffersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeaturesAndOffersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFeaturesAndOffersActionPerformed

    private void btnInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsuranceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsuranceActionPerformed

    private void btnSendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMouseEntered
        btnSend.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnSendMouseEntered

    private void btnSendMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMouseExited
        btnSend.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSendMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        btnLogout.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        btnLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnLogoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receiptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receiptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receiptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receiptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receiptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Complains;
    private javax.swing.JTextArea ComplainsBox;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel Position;
    private javax.swing.JLabel PositionLabel;
    private javax.swing.JButton btnFeaturesAndOffers;
    private javax.swing.JButton btnInsurance;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSalary;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnVacation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
