package frames;


import com.sun.javafx.image.impl.IntArgb;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;
import montg3i.Calculate;
import montg3i.Guest;
import montg3i.Hotel;
import montg3i.HotelRoom;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class ReservationForm extends javax.swing.JFrame {
    
    int RoomsNo[] = {0,0,0};
    ArrayList<HotelRoom> hrl = Hotel.getHotelRoomList();
    

    /**
     * Creates new form ReservationForm
     */
    public ReservationForm() {
        initComponents();
        btnBook.setBackground(new Color(0,0,0,0));
        btnBack.setBackground(new Color(0,0,0,0));
        btnDeparture.setBackground(new Color(0,0,0,0));
        btnNights.setBackground(new Color(0,0,0,0));
      // jPanel2.setBackground(new Color(51,204,255,90));
            //SuiteRooms.setVisible(false);
            //DoubleRooms.setVisible(false);
            //SingleRooms.setVisible(false);
            //AvailableRooms.setVisible(false);
           // Results1.setVisible(false);
           // Results2.setVisible(false);
           // Results3.setVisible(false);
           
        FirstNameBox.setText("");
        MiddleNameBox.setText("");
        LastNameBox.setText("");
        NationalIDBox.setText("");
        AgeBox.setText("0");
        MobileNumberBox.setText("");
        NationalityBox.setText("");
        NightsBox.setText("1");
        DepositBox.setText("0");
        
        FirstNameBox.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        Age = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        MiddleName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Nationality = new javax.swing.JLabel();
        NationalID = new javax.swing.JLabel();
        MobileNumber = new javax.swing.JLabel();
        MobileNumberBox = new javax.swing.JTextField();
        AgeBox = new javax.swing.JTextField();
        NationalIDBox = new javax.swing.JTextField();
        NationalityBox = new javax.swing.JTextField();
        LastNameBox = new javax.swing.JTextField();
        MiddleNameBox = new javax.swing.JTextField();
        FirstNameBox = new javax.swing.JTextField();
        btnNights = new javax.swing.JButton();
        btnDeparture = new javax.swing.JButton();
        Arrivals = new javax.swing.JLabel();
        Nights = new javax.swing.JLabel();
        Departure = new javax.swing.JLabel();
        Available_Rooms = new javax.swing.JLabel();
        TotalPayments = new javax.swing.JLabel();
        Deposit = new javax.swing.JLabel();
        RestAmount = new javax.swing.JLabel();
        DepositBox = new javax.swing.JTextField();
        TotalPaymentsLabel = new javax.swing.JLabel();
        RestAmountLabel = new javax.swing.JLabel();
        DepartureBoxDate = new com.toedter.calendar.JDateChooser();
        NightsBox = new javax.swing.JTextField();
        ArrivalsBoxDate = new com.toedter.calendar.JDateChooser();
        btnBook = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reservation Form");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1520, 845));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        btnBack.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("< Back");
        btnBack.setBorder(null);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(10, 710, 120, 45);

        Age.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Age.setForeground(new java.awt.Color(255, 255, 255));
        Age.setText("Age:");
        jPanel1.add(Age);
        Age.setBounds(30, 360, 34, 20);

        FirstName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setText("First Name:");
        jPanel1.add(FirstName);
        FirstName.setBounds(30, 90, 82, 20);

        MiddleName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        MiddleName.setForeground(new java.awt.Color(255, 255, 255));
        MiddleName.setText("Middle Name:");
        jPanel1.add(MiddleName);
        MiddleName.setBounds(30, 130, 98, 20);

        LastName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setText("Last Name:");
        jPanel1.add(LastName);
        LastName.setBounds(30, 170, 80, 20);

        Nationality.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Nationality.setForeground(new java.awt.Color(255, 255, 255));
        Nationality.setText("Nationality:");
        jPanel1.add(Nationality);
        Nationality.setBounds(30, 220, 81, 20);

        NationalID.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        NationalID.setForeground(new java.awt.Color(255, 255, 255));
        NationalID.setText("National ID:");
        jPanel1.add(NationalID);
        NationalID.setBounds(30, 260, 86, 20);

        MobileNumber.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        MobileNumber.setForeground(new java.awt.Color(255, 255, 255));
        MobileNumber.setText("Mobile Number:");
        jPanel1.add(MobileNumber);
        MobileNumber.setBounds(30, 310, 114, 20);

        MobileNumberBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileNumberBoxActionPerformed(evt);
            }
        });
        jPanel1.add(MobileNumberBox);
        MobileNumberBox.setBounds(150, 310, 195, 26);

        AgeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeBoxActionPerformed(evt);
            }
        });
        jPanel1.add(AgeBox);
        AgeBox.setBounds(150, 360, 70, 26);

        NationalIDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NationalIDBoxActionPerformed(evt);
            }
        });
        jPanel1.add(NationalIDBox);
        NationalIDBox.setBounds(150, 260, 195, 26);

        NationalityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NationalityBoxActionPerformed(evt);
            }
        });
        jPanel1.add(NationalityBox);
        NationalityBox.setBounds(150, 220, 129, 26);

        LastNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameBoxActionPerformed(evt);
            }
        });
        jPanel1.add(LastNameBox);
        LastNameBox.setBounds(150, 170, 129, 26);

        MiddleNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleNameBoxActionPerformed(evt);
            }
        });
        jPanel1.add(MiddleNameBox);
        MiddleNameBox.setBounds(150, 130, 129, 26);

        FirstNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameBoxActionPerformed(evt);
            }
        });
        jPanel1.add(FirstNameBox);
        FirstNameBox.setBounds(150, 90, 129, 20);

        btnNights.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNights.setForeground(new java.awt.Color(255, 255, 255));
        btnNights.setText("> Get Nights");
        btnNights.setBorder(null);
        btnNights.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNightsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNightsMouseExited(evt);
            }
        });
        btnNights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNightsActionPerformed(evt);
            }
        });
        jPanel1.add(btnNights);
        btnNights.setBounds(150, 500, 130, 23);

        btnDeparture.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDeparture.setForeground(new java.awt.Color(255, 255, 255));
        btnDeparture.setText("> Get Departure");
        btnDeparture.setBorder(null);
        btnDeparture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeparture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDepartureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDepartureMouseExited(evt);
            }
        });
        btnDeparture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartureActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeparture);
        btnDeparture.setBounds(150, 590, 160, 23);

        Arrivals.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Arrivals.setForeground(new java.awt.Color(255, 255, 255));
        Arrivals.setText("Arrivals:");
        jPanel1.add(Arrivals);
        Arrivals.setBounds(30, 410, 76, 20);

        Nights.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Nights.setForeground(new java.awt.Color(255, 255, 255));
        Nights.setText("Nights:");
        jPanel1.add(Nights);
        Nights.setBounds(30, 460, 76, 20);

        Departure.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Departure.setForeground(new java.awt.Color(255, 255, 255));
        Departure.setText("Departure:");
        jPanel1.add(Departure);
        Departure.setBounds(30, 550, 76, 20);

        Available_Rooms.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Available_Rooms.setForeground(new java.awt.Color(255, 255, 255));
        Available_Rooms.setText("Available Rooms:");
        jPanel1.add(Available_Rooms);
        Available_Rooms.setBounds(390, 90, 124, 20);

        TotalPayments.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        TotalPayments.setForeground(new java.awt.Color(255, 255, 255));
        TotalPayments.setText("Total Payments:");
        jPanel1.add(TotalPayments);
        TotalPayments.setBounds(390, 380, 115, 20);

        Deposit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Deposit.setForeground(new java.awt.Color(255, 255, 255));
        Deposit.setText("Deposit:");
        jPanel1.add(Deposit);
        Deposit.setBounds(390, 420, 115, 20);

        RestAmount.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RestAmount.setForeground(new java.awt.Color(255, 255, 255));
        RestAmount.setText("Rest Amount:");
        jPanel1.add(RestAmount);
        RestAmount.setBounds(390, 460, 115, 20);

        DepositBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositBoxActionPerformed(evt);
            }
        });
        jPanel1.add(DepositBox);
        DepositBox.setBounds(520, 420, 123, 26);

        TotalPaymentsLabel.setBackground(new java.awt.Color(0, 0, 0));
        TotalPaymentsLabel.setForeground(java.awt.Color.white);
        TotalPaymentsLabel.setText("jLabel19");
        jPanel1.add(TotalPaymentsLabel);
        TotalPaymentsLabel.setBounds(520, 380, 110, 20);

        RestAmountLabel.setBackground(new java.awt.Color(0, 0, 0));
        RestAmountLabel.setForeground(java.awt.Color.white);
        RestAmountLabel.setText("jLabel21");
        jPanel1.add(RestAmountLabel);
        RestAmountLabel.setBounds(520, 460, 110, 20);
        jPanel1.add(DepartureBoxDate);
        DepartureBoxDate.setBounds(150, 550, 141, 28);

        NightsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NightsBoxActionPerformed(evt);
            }
        });
        jPanel1.add(NightsBox);
        NightsBox.setBounds(150, 460, 102, 26);
        jPanel1.add(ArrivalsBoxDate);
        ArrivalsBoxDate.setBounds(150, 410, 141, 24);

        btnBook.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        btnBook.setForeground(new java.awt.Color(255, 255, 255));
        btnBook.setText(">BOOK");
        btnBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookMouseExited(evt);
            }
        });
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        jPanel1.add(btnBook);
        btnBook.setBounds(300, 670, 240, 50);

        jButton1.setText("501");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(520, 100, 59, 29);

        jButton2.setText("401");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(520, 150, 59, 29);

        jButton3.setText("301");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(520, 200, 59, 29);

        jButton4.setText("201");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(520, 250, 59, 29);

        jButton5.setText("101");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(520, 300, 59, 29);

        jButton6.setText("502");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(620, 100, 59, 29);

        jButton7.setText("402");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(620, 150, 59, 29);

        jButton8.setText("302");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(620, 200, 59, 29);

        jButton9.setText("503");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(720, 100, 59, 29);

        jButton10.setText("403");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(720, 150, 59, 29);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("New Reservation");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(280, 10, 258, 41);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(230, 50, 310, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/icons8_new_file_32px.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 10, 41, 41);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(190, 0, 810, 790);

        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1500, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed

       String FirstName = FirstNameBox.getText();
       String SecondName = MiddleNameBox.getText();
       String LastName = LastNameBox.getText();
       String NationalId = NationalIDBox.getText();
       int Age = Integer.parseInt(AgeBox.getText());
       String Phone = MobileNumberBox.getText();
       String National = NationalityBox.getText();
       int NumbersOfRooms = RoomsNo[0]+RoomsNo[1]+RoomsNo[2];
       String Arrival = new SimpleDateFormat("yyyy-MM-dd").format(ArrivalsBoxDate.getDate());
       int Nights = Integer.parseInt(NightsBox.getText());
       String Departure = new SimpleDateFormat("yyyy-MM-dd").format(DepartureBoxDate.getDate());
       double Deposite = Double.parseDouble(DepositBox.getText());
       double TotalAmount = Calculate.TotalAmount(RoomsNo, Nights, Deposite);
       
       TotalPaymentsLabel.setText((TotalAmount-Deposite) + "");
       RestAmountLabel.setText(TotalAmount + "");
       
       Hotel.AddGuestList(Guest.getGuestNextNo(), FirstName, SecondName, LastName, NationalId, Age, Phone, National, NumbersOfRooms, Arrival, Nights, Departure, Deposite, TotalAmount, "check in");
       showMessageDialog(null,"Name: " + FirstName +" "+ SecondName +" "+ LastName +"\n"+"Room No. : "+NumbersOfRooms+"\n");
       Guest.setGuestNextNo(Guest.getGuestNextNo());
       
       FirstNameBox.setText("");
       MiddleNameBox.setText("");
       LastNameBox.setText("");
       NationalIDBox.setText("");
       AgeBox.setText("0");
       MobileNumberBox.setText("");
       NationalityBox.setText("");
       NightsBox.setText("1");
       DepositBox.setText("0");
       
       FirstNameBox.requestFocus();
    }//GEN-LAST:event_btnBookActionPerformed

    private void FirstNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameBoxActionPerformed
        MiddleNameBox.requestFocus();
    }//GEN-LAST:event_FirstNameBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Receiption().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void NightsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NightsBoxActionPerformed
        try
        {
            SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
            String Arrivals_str = dformat.format(ArrivalsBoxDate.getDate());
            String Arrivals[] = Arrivals_str.split("-");
            int nights = Integer.parseInt(NightsBox.getText());
            String Departure_str = Arrivals[0] + "-" + 
                    (Integer.parseInt(Arrivals[1])+(Integer.parseInt(Arrivals[2])+nights)/(31+Integer.parseInt(Arrivals[1])%2)) + "-" + 
                    ((Integer.parseInt(Arrivals[2])+nights)%(31+Integer.parseInt(Arrivals[1])%2));
            Date departure = new SimpleDateFormat("yyyy-MM-dd").parse(Departure_str);
            DepartureBoxDate.setDate(departure);
        } 
        catch (ParseException ex) {
            Logger.getLogger(ReservationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NightsBoxActionPerformed

    private void btnDepartureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartureActionPerformed
        try
        {
            SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
            String Arrivals_str = dformat.format(ArrivalsBoxDate.getDate());
            String Arrivals[] = Arrivals_str.split("-");
            int nights = Integer.parseInt(NightsBox.getText());
            String Departure_str = Arrivals[0] + "-" + 
                    (Integer.parseInt(Arrivals[1])+(Integer.parseInt(Arrivals[2])+nights)/(31+Integer.parseInt(Arrivals[1])%2)) + "-" + 
                    ((Integer.parseInt(Arrivals[2])+nights)%(31+Integer.parseInt(Arrivals[1])%2));
            Date departure = new SimpleDateFormat("yyyy-MM-dd").parse(Departure_str);
            DepartureBoxDate.setDate(departure);
        } 
        catch (ParseException ex) {
            Logger.getLogger(ReservationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDepartureActionPerformed

    private void btnNightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNightsActionPerformed
        SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
        String Arrivals_str = dformat.format(ArrivalsBoxDate.getDate());
        String Departure_str = dformat.format(DepartureBoxDate.getDate());
        String Arrivals[] = Arrivals_str.split("-");
        String Departures[] = Departure_str.split("-");
        int nights = Integer.parseInt(Departures[2])-Integer.parseInt(Arrivals[2])
                +(Integer.parseInt(Departures[1])-Integer.parseInt(Arrivals[1]))
                *(31+Integer.parseInt(Departures[1])%2+Integer.parseInt(Arrivals[1])%2);
        NightsBox.setText(nights + "");
    }//GEN-LAST:event_btnNightsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(hrl.get(1).isAvailability())
        {
            RoomsNo[0]++;
            hrl.get(1).setAvailability(false);
            hrl.get(1).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(hrl.get(0).isAvailability())
        {
            RoomsNo[0]++;
            hrl.get(0).setAvailability(false);
            hrl.get(0).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(hrl.get(2).isAvailability())
        {
            RoomsNo[0]++;
            hrl.get(2).setAvailability(false);
            hrl.get(2).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(hrl.get(3).isAvailability())
        {
            RoomsNo[0]++;
            hrl.get(3).setAvailability(false);
            hrl.get(3).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(hrl.get(4).isAvailability())
        {
            RoomsNo[0]++;
            hrl.get(4).setAvailability(false);
            hrl.get(4).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(hrl.get(5).isAvailability())
        {
            RoomsNo[1]++;
            hrl.get(5).setAvailability(false);
            hrl.get(5).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(hrl.get(6).isAvailability())
        {
            RoomsNo[1]++;
            hrl.get(6).setAvailability(false);
            hrl.get(6).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(hrl.get(7).isAvailability())
        {
            RoomsNo[1]++;
            hrl.get(7).setAvailability(false);
            hrl.get(7).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(hrl.get(8).isAvailability())
        {
            RoomsNo[2]++;
            hrl.get(8).setAvailability(false);
            hrl.get(8).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(hrl.get(9).isAvailability())
        {
            RoomsNo[2]++;
            hrl.get(9).setAvailability(false);
            hrl.get(9).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void DepositBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositBoxActionPerformed
        int Nights = Integer.parseInt(NightsBox.getText()); 
        double Deposite = Double.parseDouble(DepositBox.getText());
        double TotalAmount = Calculate.TotalAmount(RoomsNo, Nights, Deposite);
       
        TotalPaymentsLabel.setText((TotalAmount-Deposite) + "");
        RestAmountLabel.setText(TotalAmount + "");
    }//GEN-LAST:event_DepositBoxActionPerformed

    private void MiddleNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleNameBoxActionPerformed
        LastNameBox.requestFocus();
    }//GEN-LAST:event_MiddleNameBoxActionPerformed

    private void LastNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameBoxActionPerformed
        NationalityBox.requestFocus();
    }//GEN-LAST:event_LastNameBoxActionPerformed

    private void NationalityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NationalityBoxActionPerformed
        NationalIDBox.requestFocus();
    }//GEN-LAST:event_NationalityBoxActionPerformed

    private void NationalIDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NationalIDBoxActionPerformed
        MobileNumberBox.requestFocus();
    }//GEN-LAST:event_NationalIDBoxActionPerformed

    private void MobileNumberBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileNumberBoxActionPerformed
        AgeBox.requestFocus();
    }//GEN-LAST:event_MobileNumberBoxActionPerformed

    private void AgeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeBoxActionPerformed
        NightsBox.requestFocus();
    }//GEN-LAST:event_AgeBoxActionPerformed

    private void btnNightsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNightsMouseEntered
        btnNights.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnNightsMouseEntered

    private void btnNightsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNightsMouseExited
        btnNights.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnNightsMouseExited

    private void btnDepartureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartureMouseEntered
        btnDeparture.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnDepartureMouseEntered

    private void btnDepartureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartureMouseExited
        btnDeparture.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnDepartureMouseExited

    private void btnBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookMouseEntered
        btnBook.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnBookMouseEntered

    private void btnBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookMouseExited
        btnBook.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBookMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBackMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JTextField AgeBox;
    private javax.swing.JLabel Arrivals;
    private com.toedter.calendar.JDateChooser ArrivalsBoxDate;
    private javax.swing.JLabel Available_Rooms;
    private javax.swing.JLabel Departure;
    private com.toedter.calendar.JDateChooser DepartureBoxDate;
    private javax.swing.JLabel Deposit;
    private javax.swing.JTextField DepositBox;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNameBox;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastNameBox;
    private javax.swing.JLabel MiddleName;
    private javax.swing.JTextField MiddleNameBox;
    private javax.swing.JLabel MobileNumber;
    private javax.swing.JTextField MobileNumberBox;
    private javax.swing.JLabel NationalID;
    private javax.swing.JTextField NationalIDBox;
    private javax.swing.JLabel Nationality;
    private javax.swing.JTextField NationalityBox;
    private javax.swing.JLabel Nights;
    private javax.swing.JTextField NightsBox;
    private javax.swing.JLabel RestAmount;
    private javax.swing.JLabel RestAmountLabel;
    private javax.swing.JLabel TotalPayments;
    private javax.swing.JLabel TotalPaymentsLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnDeparture;
    private javax.swing.JButton btnNights;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
