package frames;


import com.sun.javafx.image.impl.IntArgb;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;
import montg3i.Calculate;
import montg3i.Guest;
import montg3i.Hotel;
import montg3i.HotelRoom;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class ReservationForm extends javax.swing.JFrame {
    
    int RoomsNo[] = {0,0,0};
    ArrayList<HotelRoom> hrl = Hotel.getHotelRoomList();
    
    

    /**
     * Creates new form ReservationForm
     */
    public ReservationForm() {
        initComponents();
        btnBook.setBackground(new Color(0,0,0,0));
        btnBack.setBackground(new Color(0,0,0,0));
        btnDeparture.setBackground(new Color(0,0,0,0));
        btnNights.setBackground(new Color(0,0,0,0));
      
           
         if(hrl.get(0).isAvailability())
         {
             R100A.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(1).isAvailability())
         {
             R101B.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(2).isAvailability())
         {
             R102B.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(3).isAvailability())
         {
             R103C.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(4).isAvailability())
         {
             R104C.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(5).isAvailability())
         {
             R105C.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(6).isAvailability())
         {
             R200A.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(7).isAvailability())
         {
             R201B.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(8).isAvailability())
         {
             R202B.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(9).isAvailability())
         {
             R203C.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(10).isAvailability())
         {
             R204C.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(11).isAvailability())
         {
             R205C.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(12).isAvailability())
         {
             R300A.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(13).isAvailability())
         {
             R301B.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(14).isAvailability())
         {
             R302B.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(15).isAvailability())
         {
             R303C.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(16).isAvailability())
         {
             R304C.setBackground(new java.awt.Color(0, 153, 0));
         }
         if(hrl.get(17).isAvailability())
         {
             R305C.setBackground(new java.awt.Color(0, 153, 0));
         } 
           
        FirstNameBox.setText("");
        MiddleNameBox.setText("");
        LastNameBox.setText("");
        NationalIDBox.setText("");
        AgeBox.setText("0");
        MobileNumberBox.setText("");
        NationalityComboBox.getSelectedItem();
        //NationalityBox.setText("");
        NightsBox.setText("1");
        DepositBox.setText("0");
        
        FirstNameBox.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        Age = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        MiddleName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        NationalityComboBox = new javax.swing.JComboBox<>();
        Nationality = new javax.swing.JLabel();
        NationalID = new javax.swing.JLabel();
        MobileNumber = new javax.swing.JLabel();
        MobileNumberBox = new javax.swing.JTextField();
        AgeBox = new javax.swing.JTextField();
        NationalIDBox = new javax.swing.JTextField();
        LastNameBox = new javax.swing.JTextField();
        MiddleNameBox = new javax.swing.JTextField();
        FirstNameBox = new javax.swing.JTextField();
        btnNights = new javax.swing.JButton();
        btnDeparture = new javax.swing.JButton();
        Arrivals = new javax.swing.JLabel();
        Nights = new javax.swing.JLabel();
        Departure = new javax.swing.JLabel();
        Available_Rooms = new javax.swing.JLabel();
        TotalPayments = new javax.swing.JLabel();
        Deposit = new javax.swing.JLabel();
        RestAmount = new javax.swing.JLabel();
        DepositBox = new javax.swing.JTextField();
        TotalPaymentsLabel = new javax.swing.JLabel();
        RestAmountLabel = new javax.swing.JLabel();
        DepartureBoxDate = new com.toedter.calendar.JDateChooser();
        NightsBox = new javax.swing.JTextField();
        ArrivalsBoxDate = new com.toedter.calendar.JDateChooser();
        btnBook = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        R100A = new javax.swing.JButton();
        R101B = new javax.swing.JButton();
        R102B = new javax.swing.JButton();
        R103C = new javax.swing.JButton();
        R104C = new javax.swing.JButton();
        R105C = new javax.swing.JButton();
        R200A = new javax.swing.JButton();
        R201B = new javax.swing.JButton();
        R202B = new javax.swing.JButton();
        R203C = new javax.swing.JButton();
        R204C = new javax.swing.JButton();
        R205C = new javax.swing.JButton();
        R300A = new javax.swing.JButton();
        R301B = new javax.swing.JButton();
        R302B = new javax.swing.JButton();
        R303C = new javax.swing.JButton();
        R304C = new javax.swing.JButton();
        R305C = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reservation Form");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1520, 845));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        btnBack.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("< Back");
        btnBack.setBorder(null);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(10, 710, 120, 45);

        Age.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Age.setForeground(new java.awt.Color(255, 255, 255));
        Age.setText("Age:");
        jPanel1.add(Age);
        Age.setBounds(30, 360, 34, 20);

        FirstName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setText("First Name:");
        jPanel1.add(FirstName);
        FirstName.setBounds(30, 90, 82, 20);

        MiddleName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        MiddleName.setForeground(new java.awt.Color(255, 255, 255));
        MiddleName.setText("Middle Name:");
        jPanel1.add(MiddleName);
        MiddleName.setBounds(30, 130, 98, 20);

        LastName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setText("Last Name:");
        jPanel1.add(LastName);
        LastName.setBounds(30, 170, 80, 20);

        NationalityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Egyptian", "Turkish", "Italian", "Russian", "German" }));
        jPanel1.add(NationalityComboBox);
        NationalityComboBox.setBounds(150, 220, 130, 26);

        Nationality.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Nationality.setForeground(new java.awt.Color(255, 255, 255));
        Nationality.setText("Nationality:");
        jPanel1.add(Nationality);
        Nationality.setBounds(30, 220, 81, 20);

        NationalID.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        NationalID.setForeground(new java.awt.Color(255, 255, 255));
        NationalID.setText("National ID:");
        jPanel1.add(NationalID);
        NationalID.setBounds(30, 260, 86, 20);

        MobileNumber.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        MobileNumber.setForeground(new java.awt.Color(255, 255, 255));
        MobileNumber.setText("Mobile Number:");
        jPanel1.add(MobileNumber);
        MobileNumber.setBounds(30, 310, 114, 20);

        MobileNumberBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileNumberBoxActionPerformed(evt);
            }
        });
        jPanel1.add(MobileNumberBox);
        MobileNumberBox.setBounds(150, 310, 195, 30);

        AgeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeBoxActionPerformed(evt);
            }
        });
        jPanel1.add(AgeBox);
        AgeBox.setBounds(150, 360, 70, 30);

        NationalIDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NationalIDBoxActionPerformed(evt);
            }
        });
        jPanel1.add(NationalIDBox);
        NationalIDBox.setBounds(150, 260, 195, 30);

        LastNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameBoxActionPerformed(evt);
            }
        });
        jPanel1.add(LastNameBox);
        LastNameBox.setBounds(150, 170, 129, 30);

        MiddleNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleNameBoxActionPerformed(evt);
            }
        });
        jPanel1.add(MiddleNameBox);
        MiddleNameBox.setBounds(150, 130, 129, 30);

        FirstNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameBoxActionPerformed(evt);
            }
        });
        jPanel1.add(FirstNameBox);
        FirstNameBox.setBounds(150, 90, 129, 30);

        btnNights.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNights.setForeground(new java.awt.Color(255, 255, 255));
        btnNights.setText("> Get Nights");
        btnNights.setBorder(null);
        btnNights.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNightsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNightsMouseExited(evt);
            }
        });
        btnNights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNightsActionPerformed(evt);
            }
        });
        jPanel1.add(btnNights);
        btnNights.setBounds(150, 500, 130, 23);

        btnDeparture.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDeparture.setForeground(new java.awt.Color(255, 255, 255));
        btnDeparture.setText("> Get Departure");
        btnDeparture.setBorder(null);
        btnDeparture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeparture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDepartureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDepartureMouseExited(evt);
            }
        });
        btnDeparture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartureActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeparture);
        btnDeparture.setBounds(150, 590, 160, 23);

        Arrivals.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Arrivals.setForeground(new java.awt.Color(255, 255, 255));
        Arrivals.setText("Arrivals:");
        jPanel1.add(Arrivals);
        Arrivals.setBounds(30, 410, 76, 20);

        Nights.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Nights.setForeground(new java.awt.Color(255, 255, 255));
        Nights.setText("Nights:");
        jPanel1.add(Nights);
        Nights.setBounds(30, 460, 76, 20);

        Departure.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Departure.setForeground(new java.awt.Color(255, 255, 255));
        Departure.setText("Departure:");
        jPanel1.add(Departure);
        Departure.setBounds(30, 550, 76, 20);

        Available_Rooms.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Available_Rooms.setForeground(new java.awt.Color(255, 255, 255));
        Available_Rooms.setText("Available Rooms:");
        jPanel1.add(Available_Rooms);
        Available_Rooms.setBounds(400, 90, 124, 20);

        TotalPayments.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        TotalPayments.setForeground(new java.awt.Color(255, 255, 255));
        TotalPayments.setText("Total Payments:");
        jPanel1.add(TotalPayments);
        TotalPayments.setBounds(400, 430, 115, 20);

        Deposit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Deposit.setForeground(new java.awt.Color(255, 255, 255));
        Deposit.setText("Deposit:");
        jPanel1.add(Deposit);
        Deposit.setBounds(400, 480, 115, 20);

        RestAmount.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RestAmount.setForeground(new java.awt.Color(255, 255, 255));
        RestAmount.setText("Rest Amount:");
        jPanel1.add(RestAmount);
        RestAmount.setBounds(400, 530, 115, 20);

        DepositBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositBoxActionPerformed(evt);
            }
        });
        jPanel1.add(DepositBox);
        DepositBox.setBounds(530, 480, 123, 30);

        TotalPaymentsLabel.setBackground(new java.awt.Color(0, 0, 0));
        TotalPaymentsLabel.setForeground(java.awt.Color.white);
        TotalPaymentsLabel.setText("0");
        jPanel1.add(TotalPaymentsLabel);
        TotalPaymentsLabel.setBounds(530, 430, 110, 20);

        RestAmountLabel.setBackground(new java.awt.Color(0, 0, 0));
        RestAmountLabel.setForeground(java.awt.Color.white);
        RestAmountLabel.setText("0");
        jPanel1.add(RestAmountLabel);
        RestAmountLabel.setBounds(530, 530, 110, 20);
        jPanel1.add(DepartureBoxDate);
        DepartureBoxDate.setBounds(150, 550, 141, 30);

        NightsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NightsBoxActionPerformed(evt);
            }
        });
        jPanel1.add(NightsBox);
        NightsBox.setBounds(150, 460, 102, 30);
        jPanel1.add(ArrivalsBoxDate);
        ArrivalsBoxDate.setBounds(150, 410, 141, 30);

        btnBook.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        btnBook.setForeground(new java.awt.Color(255, 255, 255));
        btnBook.setText(">BOOK");
        btnBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookMouseExited(evt);
            }
        });
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        jPanel1.add(btnBook);
        btnBook.setBounds(300, 670, 240, 50);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("New Reservation");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(280, 10, 258, 41);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(230, 50, 310, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/icons8_new_file_32px.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 10, 41, 41);

        R100A.setBackground(new java.awt.Color(204, 0, 0));
        R100A.setText("100A");
        R100A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R100AActionPerformed(evt);
            }
        });
        jPanel1.add(R100A);
        R100A.setBounds(710, 360, 70, 29);

        R101B.setBackground(new java.awt.Color(204, 0, 0));
        R101B.setText("101B");
        R101B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R101BActionPerformed(evt);
            }
        });
        jPanel1.add(R101B);
        R101B.setBounds(620, 360, 70, 29);

        R102B.setBackground(new java.awt.Color(204, 0, 0));
        R102B.setText("102B");
        R102B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R102BActionPerformed(evt);
            }
        });
        jPanel1.add(R102B);
        R102B.setBounds(620, 330, 70, 29);

        R103C.setBackground(new java.awt.Color(204, 0, 0));
        R103C.setText("103C");
        R103C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R103CActionPerformed(evt);
            }
        });
        jPanel1.add(R103C);
        R103C.setBounds(530, 360, 70, 29);

        R104C.setBackground(new java.awt.Color(204, 0, 0));
        R104C.setText("104C");
        R104C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R104CActionPerformed(evt);
            }
        });
        jPanel1.add(R104C);
        R104C.setBounds(530, 330, 70, 29);

        R105C.setBackground(new java.awt.Color(204, 0, 0));
        R105C.setText("105C");
        R105C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R105CActionPerformed(evt);
            }
        });
        jPanel1.add(R105C);
        R105C.setBounds(530, 300, 70, 29);

        R200A.setBackground(new java.awt.Color(204, 0, 0));
        R200A.setText("200A");
        R200A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R200AActionPerformed(evt);
            }
        });
        jPanel1.add(R200A);
        R200A.setBounds(710, 260, 70, 29);

        R201B.setBackground(new java.awt.Color(204, 0, 0));
        R201B.setText("201B");
        R201B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R201BActionPerformed(evt);
            }
        });
        jPanel1.add(R201B);
        R201B.setBounds(620, 260, 70, 29);

        R202B.setBackground(new java.awt.Color(204, 0, 0));
        R202B.setText("202B");
        R202B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R202BActionPerformed(evt);
            }
        });
        jPanel1.add(R202B);
        R202B.setBounds(620, 230, 70, 29);

        R203C.setBackground(new java.awt.Color(204, 0, 0));
        R203C.setText("203C");
        R203C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R203CActionPerformed(evt);
            }
        });
        jPanel1.add(R203C);
        R203C.setBounds(530, 260, 70, 29);

        R204C.setBackground(new java.awt.Color(204, 0, 0));
        R204C.setText("204C");
        R204C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R204CActionPerformed(evt);
            }
        });
        jPanel1.add(R204C);
        R204C.setBounds(530, 230, 70, 29);

        R205C.setBackground(new java.awt.Color(204, 0, 0));
        R205C.setText("205C");
        R205C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R205CActionPerformed(evt);
            }
        });
        jPanel1.add(R205C);
        R205C.setBounds(530, 200, 70, 29);

        R300A.setBackground(new java.awt.Color(204, 0, 0));
        R300A.setText("300A");
        R300A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R300AActionPerformed(evt);
            }
        });
        jPanel1.add(R300A);
        R300A.setBounds(710, 160, 70, 29);

        R301B.setBackground(new java.awt.Color(204, 0, 0));
        R301B.setText("301B");
        R301B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R301BActionPerformed(evt);
            }
        });
        jPanel1.add(R301B);
        R301B.setBounds(620, 160, 70, 29);

        R302B.setBackground(new java.awt.Color(204, 0, 0));
        R302B.setText("302B");
        R302B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R302BActionPerformed(evt);
            }
        });
        jPanel1.add(R302B);
        R302B.setBounds(620, 130, 70, 29);

        R303C.setBackground(new java.awt.Color(204, 0, 0));
        R303C.setText("303C");
        R303C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R303CActionPerformed(evt);
            }
        });
        jPanel1.add(R303C);
        R303C.setBounds(530, 160, 70, 29);

        R304C.setBackground(new java.awt.Color(204, 0, 0));
        R304C.setText("304C");
        R304C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R304CActionPerformed(evt);
            }
        });
        jPanel1.add(R304C);
        R304C.setBounds(530, 130, 70, 29);

        R305C.setBackground(new java.awt.Color(204, 0, 0));
        R305C.setText("305C");
        R305C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R305CActionPerformed(evt);
            }
        });
        jPanel1.add(R305C);
        R305C.setBounds(530, 100, 70, 29);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(190, 0, 810, 790);

        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1500, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed

       String FirstName = FirstNameBox.getText();
       String SecondName = MiddleNameBox.getText();
       String LastName = LastNameBox.getText();
       String NationalId = NationalIDBox.getText();
       int Age = Integer.parseInt(AgeBox.getText());
       String Phone = MobileNumberBox.getText();
       String Nationality = (String) NationalityComboBox.getSelectedItem();
       int NumbersOfRooms = RoomsNo[0]+RoomsNo[1]+RoomsNo[2];
       String Arrival = new SimpleDateFormat("yyyy-MM-dd").format(ArrivalsBoxDate.getDate());
       int Nights = Integer.parseInt(NightsBox.getText());
       String Departure = new SimpleDateFormat("yyyy-MM-dd").format(DepartureBoxDate.getDate());
       double Deposite = Double.parseDouble(DepositBox.getText());
       double TotalAmount = Calculate.TotalAmount(RoomsNo, Nights);
       
       TotalPaymentsLabel.setText(TotalAmount + "");
       RestAmountLabel.setText((TotalAmount-Deposite) + "");
       
       Hotel.AddGuestList(Guest.getGuestNextNo(), FirstName, SecondName, LastName, NationalId, Age, Phone, Nationality, NumbersOfRooms, Arrival, Nights, Departure, Deposite, TotalAmount, "Check In");
       showMessageDialog(null,"Name: " + FirstName +" "+ SecondName +" "+ LastName +"\n"+"Room No. : "+NumbersOfRooms+"\n");
       Guest.setGuestNextNo(Guest.getGuestNextNo());
       
       FirstNameBox.setText("");
       MiddleNameBox.setText("");
       LastNameBox.setText("");
       NationalIDBox.setText("");
       AgeBox.setText("0");
       MobileNumberBox.setText("");
       NationalityComboBox.getSelectedItem();
       //NationalityBox.setText("");
       NightsBox.setText("1");
       DepositBox.setText("0");
       
       FirstNameBox.requestFocus();
    }//GEN-LAST:event_btnBookActionPerformed

    private void FirstNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameBoxActionPerformed
        MiddleNameBox.requestFocus();
    }//GEN-LAST:event_FirstNameBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Receiption().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void NightsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NightsBoxActionPerformed
        try
        {
            SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
            String Arrivals_str = dformat.format(ArrivalsBoxDate.getDate());
            String Departure_str = Calculate.CalculateDate(Arrivals_str, Integer.parseInt(NightsBox.getText()));
            Date departure = new SimpleDateFormat("yyyy-MM-dd").parse(Departure_str);
            DepartureBoxDate.setDate(departure);
        } 
        catch (ParseException ex) {
            Logger.getLogger(ReservationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NightsBoxActionPerformed

    private void btnDepartureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartureActionPerformed
        try
        {
            SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
            String Arrivals_str = dformat.format(ArrivalsBoxDate.getDate());
            String Departure_str = Calculate.CalculateDate(Arrivals_str, Integer.parseInt(NightsBox.getText()));
            Date departure = new SimpleDateFormat("yyyy-MM-dd").parse(Departure_str);
            DepartureBoxDate.setDate(departure);
        } 
        catch (ParseException ex) {
            Logger.getLogger(ReservationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDepartureActionPerformed

    private void btnNightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNightsActionPerformed
        SimpleDateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
        String Arrivals_str = dformat.format(ArrivalsBoxDate.getDate());
        String Departure_str = dformat.format(DepartureBoxDate.getDate());
        int nights = Calculate.CalculateNights(Arrivals_str, Departure_str);
        NightsBox.setText((nights) + "");
    }//GEN-LAST:event_btnNightsActionPerformed

    private void DepositBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositBoxActionPerformed
        int Nights = Integer.parseInt(NightsBox.getText()); 
        double Deposite = Double.parseDouble(DepositBox.getText());
        double TotalAmount = Calculate.TotalAmount(RoomsNo, Nights);
       
        TotalPaymentsLabel.setText(TotalAmount + "");
        RestAmountLabel.setText((TotalAmount-Deposite) + "");
    }//GEN-LAST:event_DepositBoxActionPerformed

    private void MiddleNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleNameBoxActionPerformed
        LastNameBox.requestFocus();
    }//GEN-LAST:event_MiddleNameBoxActionPerformed

    private void LastNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameBoxActionPerformed
        NationalIDBox.requestFocus();
    }//GEN-LAST:event_LastNameBoxActionPerformed

    private void NationalIDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NationalIDBoxActionPerformed
        MobileNumberBox.requestFocus();
    }//GEN-LAST:event_NationalIDBoxActionPerformed

    private void MobileNumberBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileNumberBoxActionPerformed
        AgeBox.requestFocus();
    }//GEN-LAST:event_MobileNumberBoxActionPerformed

    private void AgeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeBoxActionPerformed
        NightsBox.requestFocus();
    }//GEN-LAST:event_AgeBoxActionPerformed

    private void btnNightsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNightsMouseEntered
        btnNights.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnNightsMouseEntered

    private void btnNightsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNightsMouseExited
        btnNights.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnNightsMouseExited

    private void btnDepartureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartureMouseEntered
        btnDeparture.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnDepartureMouseEntered

    private void btnDepartureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartureMouseExited
        btnDeparture.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnDepartureMouseExited

    private void btnBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookMouseEntered
        btnBook.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnBookMouseEntered

    private void btnBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookMouseExited
        btnBook.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBookMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBackMouseExited

    private void R100AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R100AActionPerformed
        if(hrl.get(0).isAvailability())
        {
            RoomsNo[0]++;
            hrl.get(0).setAvailability(false);
            hrl.get(0).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R100A.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R100AActionPerformed

    private void R101BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R101BActionPerformed
        if(hrl.get(1).isAvailability())
        {
            RoomsNo[1]++;
            hrl.get(1).setAvailability(false);
            hrl.get(1).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R101B.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R101BActionPerformed

    private void R102BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R102BActionPerformed
        if(hrl.get(2).isAvailability())
        {
            RoomsNo[1]++;
            hrl.get(2).setAvailability(false);
            hrl.get(2).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R102B.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R102BActionPerformed

    private void R103CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R103CActionPerformed
        if(hrl.get(3).isAvailability())
        {
            RoomsNo[2]++;
            hrl.get(3).setAvailability(false);
            hrl.get(3).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R103C.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R103CActionPerformed

    private void R104CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R104CActionPerformed
        if(hrl.get(4).isAvailability())
        {
            RoomsNo[2]++;
            hrl.get(4).setAvailability(false);
            hrl.get(4).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R104C.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R104CActionPerformed

    private void R105CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R105CActionPerformed
        if(hrl.get(5).isAvailability())
        {
            RoomsNo[2]++;
            hrl.get(5).setAvailability(false);
            hrl.get(5).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R105C.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R105CActionPerformed

    private void R200AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R200AActionPerformed
        if(hrl.get(6).isAvailability())
        {
            RoomsNo[0]++;
            hrl.get(6).setAvailability(false);
            hrl.get(6).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R200A.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R200AActionPerformed

    private void R201BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R201BActionPerformed
        if(hrl.get(7).isAvailability())
        {
            RoomsNo[1]++;
            hrl.get(7).setAvailability(false);
            hrl.get(7).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R201B.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R201BActionPerformed

    private void R202BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R202BActionPerformed
        if(hrl.get(8).isAvailability())
        {
            RoomsNo[1]++;
            hrl.get(8).setAvailability(false);
            hrl.get(8).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R202B.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R202BActionPerformed

    private void R203CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R203CActionPerformed
        if(hrl.get(9).isAvailability())
        {
            RoomsNo[2]++;
            hrl.get(9).setAvailability(false);
            hrl.get(9).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R203C.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R203CActionPerformed

    private void R204CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R204CActionPerformed
        if(hrl.get(10).isAvailability())
        {
            RoomsNo[2]++;
            hrl.get(10).setAvailability(false);
            hrl.get(10).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R204C.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R204CActionPerformed

    private void R205CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R205CActionPerformed
        if(hrl.get(11).isAvailability())
        {
            RoomsNo[2]++;
            hrl.get(11).setAvailability(false);
            hrl.get(11).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R205C.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R205CActionPerformed

    private void R300AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R300AActionPerformed
        if(hrl.get(12).isAvailability())
        {
            RoomsNo[0]++;
            hrl.get(12).setAvailability(false);
            hrl.get(12).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R300A.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R300AActionPerformed

    private void R301BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R301BActionPerformed
        if(hrl.get(13).isAvailability())
        {
            RoomsNo[1]++;
            hrl.get(13).setAvailability(false);
            hrl.get(13).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R301B.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R301BActionPerformed

    private void R302BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R302BActionPerformed
        if(hrl.get(14).isAvailability())
        {
            RoomsNo[1]++;
            hrl.get(14).setAvailability(false);
            hrl.get(14).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R302B.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R302BActionPerformed

    private void R303CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R303CActionPerformed
        if(hrl.get(15).isAvailability())
        {
            RoomsNo[2]++;
            hrl.get(15).setAvailability(false);
            hrl.get(15).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R303C.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R303CActionPerformed

    private void R304CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R304CActionPerformed
        if(hrl.get(16).isAvailability())
        {
            RoomsNo[2]++;
            hrl.get(16).setAvailability(false);
            hrl.get(16).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R304C.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R304CActionPerformed

    private void R305CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R305CActionPerformed
        if(hrl.get(17).isAvailability())
        {
            RoomsNo[2]++;
            hrl.get(17).setAvailability(false);
            hrl.get(17).setGuestNo(Guest.getGuestNextNo());
            Hotel.setHotelRoomList(hrl);
            R305C.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_R305CActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JTextField AgeBox;
    private javax.swing.JLabel Arrivals;
    private com.toedter.calendar.JDateChooser ArrivalsBoxDate;
    private javax.swing.JLabel Available_Rooms;
    private javax.swing.JLabel Departure;
    private com.toedter.calendar.JDateChooser DepartureBoxDate;
    private javax.swing.JLabel Deposit;
    private javax.swing.JTextField DepositBox;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNameBox;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastNameBox;
    private javax.swing.JLabel MiddleName;
    private javax.swing.JTextField MiddleNameBox;
    private javax.swing.JLabel MobileNumber;
    private javax.swing.JTextField MobileNumberBox;
    private javax.swing.JLabel NationalID;
    private javax.swing.JTextField NationalIDBox;
    private javax.swing.JLabel Nationality;
    private javax.swing.JComboBox<String> NationalityComboBox;
    private javax.swing.JLabel Nights;
    private javax.swing.JTextField NightsBox;
    private javax.swing.JButton R100A;
    private javax.swing.JButton R101B;
    private javax.swing.JButton R102B;
    private javax.swing.JButton R103C;
    private javax.swing.JButton R104C;
    private javax.swing.JButton R105C;
    private javax.swing.JButton R200A;
    private javax.swing.JButton R201B;
    private javax.swing.JButton R202B;
    private javax.swing.JButton R203C;
    private javax.swing.JButton R204C;
    private javax.swing.JButton R205C;
    private javax.swing.JButton R300A;
    private javax.swing.JButton R301B;
    private javax.swing.JButton R302B;
    private javax.swing.JButton R303C;
    private javax.swing.JButton R304C;
    private javax.swing.JButton R305C;
    private javax.swing.JLabel RestAmount;
    private javax.swing.JLabel RestAmountLabel;
    private javax.swing.JLabel TotalPayments;
    private javax.swing.JLabel TotalPaymentsLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnDeparture;
    private javax.swing.JButton btnNights;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
