package frames;

import java.awt.Color;
import montg3i.Hotel;

public class ResortHomePage extends javax.swing.JFrame {

    /**
     * Creates new form ResortHomePage
     */
    public ResortHomePage() {
        initComponents();
        
        Hotel.LoadData();
        
        
        jPanel1.setBackground(new Color(0,0,0,50));
        btnGuest.setForeground(Color.WHITE);
        btnStaff.setForeground(Color.WHITE);
        btnOffer.setForeground(Color.RED);
        btnStaff.setBackground(new Color(0,0,0,0));
        btnGuest.setBackground(new Color(0,0,0,0));
        btnOffer.setBackground(new Color(0,0,0,0));
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOffer = new javax.swing.JButton();
        btnStaff = new javax.swing.JButton();
        btnGuest = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1300, 905));
        setPreferredSize(new java.awt.Dimension(1285, 853));
        setSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        btnOffer.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnOffer.setForeground(new java.awt.Color(255, 51, 51));
        btnOffer.setText("OFFER");
        btnOffer.setBorder(null);
        btnOffer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOffer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOfferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOfferMouseExited(evt);
            }
        });
        btnOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfferActionPerformed(evt);
            }
        });
        getContentPane().add(btnOffer);
        btnOffer.setBounds(1160, 20, 50, 40);

        btnStaff.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnStaff.setText("Staff");
        btnStaff.setBorder(null);
        btnStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStaffMouseExited(evt);
            }
        });
        btnStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffActionPerformed(evt);
            }
        });
        getContentPane().add(btnStaff);
        btnStaff.setBounds(810, 20, 80, 40);

        btnGuest.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnGuest.setText("Guest");
        btnGuest.setBorder(null);
        btnGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuestMouseExited(evt);
            }
        });
        btnGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuestActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuest);
        btnGuest.setBounds(370, 20, 70, 40);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/icons8_user_50px_9.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 10, 50, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/icons8_user_groups_50px_2.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(750, 10, 50, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/icons8_discount_30px.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1130, 20, 30, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/montg3iii.JPG"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnStaffActionPerformed

    private void btnGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuestActionPerformed
       new Guest().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGuestActionPerformed

    private void btnStaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStaffMouseExited
        btnStaff.setForeground(Color.white);       
    }//GEN-LAST:event_btnStaffMouseExited

    private void btnStaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStaffMouseEntered
        btnStaff.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnStaffMouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        
    }//GEN-LAST:event_jLabel1MouseExited

    private void btnGuestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuestMouseEntered
        btnGuest.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnGuestMouseEntered

    private void btnGuestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuestMouseExited
           btnGuest.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnGuestMouseExited

    private void btnOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfferActionPerformed
            new Offer().setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnOfferActionPerformed

    private void btnOfferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOfferMouseEntered
        btnOffer.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnOfferMouseEntered

    private void btnOfferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOfferMouseExited
        btnOffer.setForeground(Color.RED);
    }//GEN-LAST:event_btnOfferMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResortHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResortHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResortHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResortHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResortHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuest;
    private javax.swing.JButton btnOffer;
    private javax.swing.JButton btnStaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
